<a href="https://colab.research.google.com/github/rakibulislam0101/Python-Basic/blob/main/Artificial_Neuron_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [ ]:
import numpy as np

a = np.array([
    [2,3,1,3,5,8,9],
    [1,2,3,5,4,6,5],
])
a.shape

(2, 7)

In [ ]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],])
y.shape
y.ndim

2

In [ ]:
z = np.array([[
    [6,3,2,1,4],
    [8,6,4,2,5],
]])
z.dtype

f = np.array([
    [3.0,5,7,1,5,9],
    [9,5,1,7,5,3],
])
f.dtype

dtype('float64')

In [ ]:
A = np.array([
    [2,5,8,9,6,3],
    [7,4,1,8,5,2],

])

A.shape
A.size

B = np.array([
    ['A','B','C','D'],
    ['E','F','G','H'],

])
B.shape
B.size

8

In [ ]:
x = np.zeros((4,4,4))
x

y = np.zeros((2,5,2),dtype='int')
y

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
a = np.ones((3,2,2),dtype='int')
a

c = np.ones((3,2,4),dtype='int')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [ ]:
x = np.ones((3,2,3),dtype='int')
x

y = np.zeros((3,3,4),dtype='int')
y

a = np.array([1,2,3,4,5])

b = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10]
]])

x.nbytes, y.nbytes, a.nbytes, b.nbytes

z = np.zeros((2,3,4))
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z.data, x.data, y.data, a.data, b.data

(<memory at 0x7cdd9767d030>,
 <memory at 0x7cdd9767d5d0>)

In [ ]:
full_1 = np.full((3,3),5)
full_1

full_2 = np.full((4,4),0)
full_2

full_3 = np.full((3,2,5),1)
full_3

full_4 = np.full((3,6),9)
full_4

full_5 = np.full((2,4,5),0)
full_5

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
identity_2 = np.identity(3,dtype='int')
identity_2

identity_3 = np.identity(4,dtype='int')
identity_3

identity_4 = np.identity(8,dtype='int')
identity_4

identity_5 = np.identity(2,dtype='int')
identity_5


array([[1, 0],
       [0, 1]])

In [ ]:
identity_5[0][1]

0

In [ ]:
A = np.random.randint(1,6, size=(2,3,3))
A

array([[[5, 2, 5],
        [1, 5, 3],
        [2, 5, 5]],

       [[1, 1, 1],
        [4, 2, 3],
        [3, 2, 5]]])

In [ ]:
A[1][2][2]

5

In [ ]:
i = np.identity((3),dtype='int')
i

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
import numpy as np
Arr_2 = np.random.randint(1,10,size=(3,5))
Arr_2

array([[8, 2, 1, 9, 8],
       [6, 8, 7, 2, 7],
       [9, 1, 4, 9, 1]])

In [ ]:
Arr_2[2][2]

4

In [ ]:
Arr_3 = np.random.randint(1,20, size=(3,4,4))
Arr_3

array([[[ 1, 15, 15, 17],
        [ 2,  9, 16, 10],
        [ 5, 17, 15,  1],
        [ 4, 13,  3, 15]],

       [[ 2, 14, 18,  9],
        [ 5,  6,  5, 17],
        [ 3,  6, 13, 11],
        [15,  8, 17,  7]],

       [[10, 17, 11, 11],
        [13,  9,  8,  3],
        [19,  7, 11,  9],
        [12, 18, 11, 10]]])

In [ ]:
Arr_3[1][2][0]

3

In [ ]:
Arr_1 = np.arange(1,11)

Arr_1[4:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
Arr_5 = np.random.randint(1,20 ,size=(4,4))
Arr_5



In [ ]:
Arr_5[0:2, 0:3]

array([[ 5, 10, 14],
       [12, 17, 13]])

In [ ]:
#manipilating array shapes

#reshape()
#resize()



In [ ]:
#reshape()

a = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5]
])
a.ndim
a.shape

np.reshape(a,(5,2)) #reshape

array([[1, 2],
       [3, 4],
       [5, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b = np.array([
    [1,2,3],
    [6,7,8],
])

np.reshape(b, (3,2))

array([[1, 2],
       [3, 6],
       [7, 8]])

In [ ]:
x = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [2,6,5,8,7]

])
x


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  6,  5,  8,  7]])

In [ ]:
np.reshape(x,(5,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  2,  6],
       [ 5,  8,  7]])

In [ ]:

b_ = np.array([
    [1,2,3],
    [4,5,6]
])

b_.shape

(2, 3)

In [ ]:
x = np.array([
    [1,2,3],
    [4,5,6],
])

a_resize = np.resize(x,(3,2))
a_resize

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
y = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

y_resize = np.resize(y,(4,1))
y_resize

array([[1],
       [2],
       [3],
       [4]])

In [ ]:

    # ['A','B','C','D'],
    # ['E','F','G','H','I']

z = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

z_resize = np.resize(z,(4,2))
z_resize

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
import numpy as np
a = np.random.randint(1,10,(4,4))
a

array([[3, 7, 4, 6],
       [3, 7, 8, 8],
       [1, 8, 2, 1],
       [3, 6, 6, 9]])

In [ ]:
a_raveld = np.ravel(a)
a_raveld

array([7, 3, 9, 2, 6, 7, 2, 8, 2, 2, 1, 6, 6, 3, 6, 5])

In [ ]:
x = np.random.randint(1,10,(3,2))
x

array([[6, 1],
       [2, 8],
       [5, 9]])

In [ ]:
x_raveld = np.ravel(x)
x_raveld

array([6, 1, 2, 8, 5, 9])

In [ ]:
y = np.random.randint(1,25,(3,3))
y

array([[18, 21, 19],
       [11, 22,  2],
       [12, 24,  4]])

In [ ]:
y_flattend = y.flatten()
y_flattend

array([18, 21, 19, 11, 22,  2, 12, 24,  4])

In [ ]:
y_flattend[0]

18

In [ ]:
a = np.random.randint(1,5,(2,3))
a

array([[3, 4, 1],
       [1, 2, 1]])

In [ ]:
a.shape = (3,2)
a

array([[3, 4],
       [1, 1],
       [2, 1]])

In [5]:
import numpy as np

b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a = 2*b
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
import numpy as np
x = np.arange(1,10).reshape(3,3)


In [26]:
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.hstack((x,y))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [34]:
np.column_stack((x,y))


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [35]:
import numpy as np

a = np.array([
    [1,5,9,7,5,3],
    [3,5,7,1,5,9]
])

b = np.array([
    [9,5,1,3,5,7],
    [7,5,3,1,5,9]
])

np.column_stack((a,b))

array([[1, 5, 9, 7, 5, 3, 9, 5, 1, 3, 5, 7],
       [3, 5, 7, 1, 5, 9, 7, 5, 3, 1, 5, 9]])

In [36]:
a = np.array([
    [1,5,9,7,5,3],
    [3,5,7,1,5,9]
])

b = np.array([
    [9,5,1,3,5,7],
    [7,5,3,1,5,9]
])

np.vstack((a,b)) #vartical stack

array([[1, 5, 9, 7, 5, 3],
       [3, 5, 7, 1, 5, 9],
       [9, 5, 1, 3, 5, 7],
       [7, 5, 3, 1, 5, 9]])

In [37]:
np.row_stack((a,b))

array([[1, 5, 9, 7, 5, 3],
       [3, 5, 7, 1, 5, 9],
       [9, 5, 1, 3, 5, 7],
       [7, 5, 3, 1, 5, 9]])

In [38]:
np.dstack((a,b))

array([[[1, 9],
        [5, 5],
        [9, 1],
        [7, 3],
        [5, 5],
        [3, 7]],

       [[3, 7],
        [5, 5],
        [7, 3],
        [1, 1],
        [5, 5],
        [9, 9]]])